### ISSUE TITLE
Stop the "float" on recurring runs

### ISSUE THREAD

**Issue by cshowersPersonal** [aws-solutions/distributed-load-testing-on-aws#141] opened 2023-10-20 14:55 UTC
**Describe the bug**
1. The scheduled time for a recurring daily run floats .  Meaning over time it changes slightly each run.  

2. Also if you kick off the daily scheduled run, the next scheduled time is changed.

**To Reproduce**
1. Create a daily recurring test.
Let it run for a few days.
Watch the time change over time.

2. Create a daily recurring test
Run it manually
Observe the next scheduled time has changed.

**Expected behavior**
The saved scheduled time should remain.  I cannot find any value in how it operates today.

The original scheduled time in the screenshot was 6AM .  This is a minor example, I typically adjust it every time I change the script.  I've seen it deviate as much as 7 minutes in the past.
![image (4)](https://github.com/aws-solutions/distributed-load-testing-on-aws/assets/145483468/8a349236-9464-46df-8382-dc4f8fb8dc39)

**Comment by kamyarz-aws** [comment] 2023-10-20 19:47
Has it ever been more than 15 minutes?

**Comment by cshowersPersonal** [comment] 2023-10-20 20:23
For #1 not that I've noticed. Like I said I update tests regularly and when I do I fix the start time.

For #2 it's really more of an annoying problem.  If you have a nightly run that you want to run outside of the scheduled time, the new scheduled time gets updated to the time you're running off-schedule.  Which then requires you to edit the test and fix the time.  

Bottom line it doesn't make sense that scheduled time changes to last executed time after the test is saved.

**Comment by cshowersPersonal** [comment] 2023-10-20 20:28
Should also mention that we run automated tests and performance tests through the night after our US personnel stop working but before our poland personnel start working.  It's only about a 5 hour window and our timings matter because they can step on each other and skew results.

**Comment by kamyarz-aws** [comment] 2023-10-20 20:32
I see. I look into it and try to fix it in our next releases.

**Comment by kamyarz-aws** [comment] 2023-10-23 15:55
For the first Issue, Can you confirm if step function was triggered on time?

For the second one, this doesnt strike me as a bug as you just mentioned. We can create a feature request to add like a exception times so your original time wont change but you can kick a non-scheduled test.

**Comment by cshowersPersonal** [comment] 2023-10-23 17:27
For first question, sorry I do not understand.  Can you please explain?  For second question:  The SCHEDULED start time is being replaced by LAST RUN TIME.  Seems like a bug, but if that's a feature then ya it would be really nice if the SCHEDULED time stays the SCHEDULED time unless the test is edited and the scheduled time is changed.

**Comment by kamyarz-aws** [comment] 2023-10-30 13:34
For the second one, That is like the expected behaviour. It is designed to set the time automatically only if you start a test now and set the test to rerun daily/weekly on the same time you started the test. Now if you set a time, but start at some other time, the second time takes precedence. That is why I meant when I say it is not a bug. Now we can work out a feature so through GUI maybe you select a checkbox to not override the time, or something like that. . For the first one, scratch what I said about step functions. It is a bug and I am trying to address it.

**Comment by kamyarz-aws** [comment] 2023-11-08 13:13
@cshowersPersonal This will be addressed in our next release

**Comment by kamyarz-aws** [comment] 2023-11-16 15:19
@cshowersPersonal I released a new patch that should resolve this issue.

**Closed** 2023-11-23 18:37 UTC
Labels: bug
