### ISSUE TITLE
us-west-2 deploy problem --> fatal error: An error occurred (404) when calling the HeadObject operation: Key "public/test-scenarios/jmeter/aaa.jmx" does not exist

### ISSUE THREAD

**Issue by flap** [aws-solutions/distributed-load-testing-on-aws#97] opened 2022-08-03 03:38 UTC
**Describe the bug**
S3 files not found at runtime tests when create a test with upload jmx file ( or jmx inside a zip file ) at us-west-2 region.

**To Reproduce**
1- Deploy solution at us-west-2 region 
2- Create a test with jmeter file

**Expected behavior**

**Please complete the following information about the solution:**
- [x] Version: v2.0.2
- [x] Region: us-west-2
- [ ] Was the solution modified from the version published on this repository? No.
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? Yes
- [x] Were there any errors in the CloudWatch Logs?

S3_BUCKET:: summit-sp-oregon-***
--
TEST_ID:: ***
TEST_TYPE:: jmeter
FILE_TYPE:: script
PREFIX:: 331.80:85:20T30-80-2202
UUID c9e4cb57-bc79-4bc1-8a5c-4b5180b4e760
Download test scenario
Completed 293 Bytes/293 Bytes (3.2 KiB/s) with 1 file(s) remainingdownload: s3://summit-sp-oregon-***/test-scenarios/fzNUPufrkv.json to ./test.json
cp /bzt-configs/*.jar /root/.bzt/jmeter-taurus/5.4.2/lib
**fatal error: An error occurred (404) when calling the HeadObject operation: Key "public/test-scenarios/jmeter/fzNUPufrkv.jmx" does not exist**
Running test
fzNUPufrkv 03:00:20 INFO: Taurus CLI Tool v1.16.3
fzNUPufrkv 03:00:20 INFO: Starting with configs: ['/root/.bzt-rc', 'test.json']
fzNUPufrkv 03:00:20 INFO: Configuring...
fzNUPufrkv 03:00:20 INFO: Artifacts dir: /tmp/artifacts
fzNUPufrkv 03:00:20 INFO: Preparing...
fzNUPufrkv 03:00:21 WARNING: Could not find location at path: fzNUPufrkv.jmx
fzNUPufrkv 03:00:21 WARNING: Could not find location at path: fzNUPufrkv.jmx
fzNUPufrkv 03:00:21 WARNING: Failed to check for updates
fzNUPufrkv 03:00:22 ERROR: Internal Error: XML parsing failed for file fzNUPufrkv.jmx: Error reading file 'fzNUPufrkv.jmx': failed to load external entity "fzNUPufrkv.jmx"
fzNUPufrkv 03:00:22 INFO: Post-processing...
fzNUPufrkv 03:00:22 INFO: Artifacts dir: /tmp/artifacts
fzNUPufrkv 03:00:22 WARNING: Done performing with code: 1
cat: fzNUPufrkv.jmx: No such file or directory
Files to upload as results
There might be an error happened while the test.

**Screenshots**
N/A

**Additional context**
I did a manual upload of jmx file at expected path and when I run test again, I got sucess!

**Comment by jbouse** [comment] 2022-09-23 21:48
I can confirm seeing this same behavior when setting up a JMeter test using a ZIP file. This is appears to be a regression as the older 2.x version did not have this issue uploading the file.

**Comment by G-Lenz** [comment] 2022-11-21 18:50
Thank you for bringing this to our attention. We have added this to our backlog to investigate further.

**Comment by tomazellifelipe** [comment] 2023-03-23 20:26
Can confirm, having the same problem at v3.0.0

**Comment by jillesmc** [comment] 2023-07-04 20:40
Apparently the problem occurs because the file is not even sent to S3.
There is a CORS problem when defining a custom domain for the DLT Console, which is behind the cloudfront.

There is another issue talking about this.
#65

**Comment by kamyarz-aws** [comment] 2023-08-29 21:32
As specified in https://github.com/aws-solutions/distributed-load-testing-on-aws/issues/97#issuecomment-1620724108 I think you should refer to the solution provided in https://github.com/aws-solutions/distributed-load-testing-on-aws/issues/65 and if it resolved the issue for you as well, please let us know so we close this issue.

**Closed** 2023-10-06 14:26 UTC
Labels: bug
