### ISSUE TITLE
AWS DLT JMeter test hangs after finishing the test

### ISSUE THREAD

**Issue by LeslieMurphy** [aws-solutions/distributed-load-testing-on-aws#210] opened 2024-08-23 23:05 UTC
**Describe the bug**
Running a test at 10 VU with a ramp of 5 minutes and hold of 2 minutes works.  Changing that test to be 40VU will hang  - the test never changes to completed status and we do not get the JTL file etc.

**To Reproduce**
Unclear - some of our scripts work; others have this issue.  We cannot determine the way to isolate the issue since visibility into the fargate container is not possible

**Expected behavior**
Test should complete!  Even if there is some sort of hang up - after the allotted time for the test - the DLT tool / Taurus should give us whatever results it has - even if it for some reason has to truncate the results!

**Please complete the following information about the solution:**
- Version: we tried with 3.2.9 and also latest - both have this issue
- Region: us-east-1
- Was the solution modified from the version published on this repository? NO

Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?  YES
Were there any errors in the CloudWatch Logs? We dont see any - is there a specific log to check?

**Screenshots**
N/A

**Additional context**
Tried various combinations - e.g. running 40 VU for 30 second ramp up with 10 second hold WORKS.  But same test wtih 5 min ramp up and 2 min hold hangs indefinitely.  We have no clue what could cause this!

**Comment by kamyarz-aws** [comment] 2024-08-26 12:29
@LeslieMurphy 

Do you have access to ECS logs in you AWS account? ECS generates the logs while running the test and it stays there for an hour. If you can run the tests twice. Once where it doesnt hang and once where it does, you will have two logs and you can provide that to me, to get a better picture on where the issue is getting created and how we can resolve it.

**Comment by LeslieMurphy** [comment] 2024-08-26 13:18
After additional research were able to confirm that the JMeter process in the fargate tasks was never finishing.

The root cause was that we were getting connection timeouts for the HTTP requests, due to overloading the target system.  

The fix is to set HTTP request defaults for the connect and response timeout in JMeter.

Is it possible for a future enhancement to send a stoptest request into the JMeter port 4446 if the test is not complete within the configured duration plus a grace period?  e.g. for a ramp of 3 minutes and hold for 10, send a stoptest after 15 minutes.

This article helped me:
https://stackoverflow.com/questions/71166168/jmeter-unable-to-notify-test-listeners-and-summarize-test-results

**Comment by kamyarz-aws** [comment] 2024-08-26 13:24
Sure, we can add that to our backlog? 

So can I close this ticket or change the tagging from the bug?

**Comment by LeslieMurphy** [comment] 2024-08-26 13:31
YES PLEASE!

**Closed** 2024-08-26 13:37 UTC
Labels: bug

**Comment by kamyarz-aws** [comment] 2024-08-26 13:42
@LeslieMurphy Btw seems like you use DLT regularly, We do like to hear your feedback on the tool and if you have any suggestions/features that we could add to our backlog for future development.
Let me know how we can connect. If you have a TAM in AWS we can sync up with them to schedule a call

**Comment by LeslieMurphy** [comment] 2024-08-26 14:57
Yes - we definitely can connect!  Can you message me on LinkedIn? 

Let me check with my client and arrange for their TAM to set up a call.

**Comment by kamyarz-aws** [comment] 2024-08-26 15:56
Can you give me the link to your linkedin please?

**Comment by LeslieMurphy** [comment] 2024-08-26 16:51
https://www.linkedin.com/in/leslielmurphy/

**Comment by kamyarz-aws** [comment] 2024-09-12 13:09
@LeslieMurphy I cant send you message through Linkedin InMail.

**Comment by LeslieMurphy** [comment] 2024-09-12 13:30
Can you send an email to lex,murphz at ePerforman$eGroup dot com with x = s and z = y and $ = c

**Comment by kamyarz-aws** [comment] 2024-09-12 13:38
Got it!
